name: Docker Build and Push
description: A Composite action to Build a Docker image and push it to Docker Hub

inputs:
  docker-username:
    description: 'Docker Hub username'
    required: true
  docker-token:
    description: 'Docker Hub access token'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  dockerfile-path:
    description: 'Dockerfile path'
    required: true

outputs:
  result:
    description: 'Result of the action: success or fail'
    value: ${{ steps.final_result.outputs.result }}

runs:
  using: 'composite'

  steps:
    - name: Authenticate to Docker Hub
      shell: bash
      id: login
      run: |
        if echo "${{ inputs.docker-token }}" | docker login -u "${{ inputs.docker-username }}" --password-stdin; then
          echo "Login Successful"
          echo "result=success" >> $GITHUB_OUTPUT
        else
          echo "Login Failed"
          echo "result=login failed" >> $GITHUB_OUTPUT
        fi

    - name: Build Docker image
      shell: bash
      id: build
      if: steps.login.outputs.result == 'success'
      run: |
        if docker build -t "${{ inputs.docker-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}" -f ${{inputs.dockerfile-path}} .; then
          echo "Build Successful"
          echo "result=success" >> $GITHUB_OUTPUT
        else
          echo "Build Failed"
          echo "result=build failed" >> $GITHUB_OUTPUT
        fi

    - name: Push Docker image
      shell: bash
      id: push
      if: steps.login.outputs.result == 'success' && steps.build.outputs.result == 'success'
      run: |
        if docker push "${{ inputs.docker-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"; then
          echo "Push Successful"
          echo "result=success" >> $GITHUB_OUTPUT
        else
          echo "Push Failed"
          echo "result=push failed" >> $GITHUB_OUTPUT
        fi

    - name: Set Output result
      shell: bash
      id: final_result
      run: |
        login_result=${{ steps.login.outputs.result }}
        build_result=${{ steps.build.outputs.result }}
        push_result=${{ steps.push.outputs.result }}

        if [ "$login_result" != "success" ]; then
          echo "result=failure(login failed)" >> $GITHUB_OUTPUT
        elif [ "$build_result" != "success" ]; then
          echo "result=failure(build failed)" >> $GITHUB_OUTPUT
        elif [ "$push_result" != "success" ]; then
          echo "result=failure(push failed)" >> $GITHUB_OUTPUT
        else
          echo "result=success" >> $GITHUB_OUTPUT
        fi
