name: First Workflow

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "Hello, Minar"
          echo "Hello, World"
