name: Conditional Workflow

on:
  workflow_dispatch:

# on:
#   push:
#     paths:
#       - 'backend/**'

jobs:
  conditional-job:
    uses: itsMinar/gh-action-demo/.github/workflows/12-reuseable-workflow.yml@main
