name: Predefined Workflow

# event
on:
  workflow_dispatch:

# jobs
jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Nodejs Version
        run: node -v

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
